### ISSUE TITLE
添加datagridview 最大化时错误

### ISSUE THREAD

**Issue by FreeVB** [hlz2516/AutoScaleHelper#1]
![16](https://github.com/hlz2516/AutoScaleHelper/assets/30093956/bd674bca-6b8d-4423-bfa1-29fc271c83df)

如图，演示项目中放一个datagridview后再调整form大小，就会出现这个错误。是不支持还是需要别的设置？
已经Star.
(QQ:289778005)

**Comment by hlz2516** [comment]
目前只是搭建了一个基础框架，还没有对winform中自带的各种控件进行测试和特殊处理。

**Comment by hlz2516** [comment]
目前该类库已适配dgv，可以在nuget中搜索AutoScaleHelper安装使用了。有什么问题再提issue。
