### ISSUE TITLE
WPF

### ISSUE THREAD

**Issue by MajorMayer** [hlz2516/AutoScaleHelper#2]

**Comment by MajorMayer** [comment]
如何在wpf中使用

**Comment by hlz2516** [comment]
这个类库是针对winform框架的，本人没有试过在wpf中使用，也不建议你在wpf中使用。    
根据我的了解，WPF在界面布局上比winform灵活得多，你可以使用viewbox或者dockpanel等布局控件来完成你想要的效果。
