### ISSUE TITLE
大佬你好，我遇到一个字体加粗问题

### ISSUE THREAD

**Issue by demobugcy** [hlz2516/AutoScaleHelper#4]
程序启动是最大化展示，然后最小化或者窗体大小改变，发现字体会变，从原来的加粗变成不加粗，原来的 字体会变成其他字体，我在案例里面的代码试了下，只要窗体大小改变，加粗字体就会变不加粗

**Comment by hlz2516** [comment]
该问题已修复，最新包已经放在该仓库的release下，也可以通过readme里的下载链接直接下载nuget包。用最新包再试下，如果没问题的话就把这个issue关闭了吧。

**Comment by demobugcy** [comment]
感谢大佬😁
