### ISSUE TITLE
button字体大小问题

### ISSUE THREAD

**Issue by demobugcy** [hlz2516/AutoScaleHelper#5]
又来麻烦大佬了
案例中 的 Form_Button  将字体设置  较大（宋体, 122pt, style=Bold）的时候，去运行项目 ，启动的时候展示的字体大小是 设计里面的字体大小。但是只要窗体大小改变，字体就会变小。
比如原来设置成 122pt，改变窗体之后，似乎会 变成 72pt

但是字体原来如果小于72pt就不会

**Comment by hlz2516** [comment]
目前只支持默认的国际字体大小（8-72）和中文字体大小（八号-初号）范围内的缩放变化，超过该范围就不支持了。这个不算Bug吧，因为本来就是这么设计的，一般来讲这个支持的范围够用了。如果后续我有空的话，可能会加个让字体随容器高度线性变化的缩放模式吧，你可以自己看下源码是怎么处理字体缩放的，然后魔改源码给自己的项目用。

**Comment by hlz2516** [comment]
最新版（v1.0.6.2）已经开放了字体缩放算法的虚拟方法，你可以继承AutoScale/TextScale类，然后重写SetControlFontSize方法即可。使用方法可参考demo里的**6_字体自适应**下新加的demo3和demo4。

**Comment by demobugcy** [comment]
好的，谢谢大佬，麻烦了😁。最近比较忙，之前看了眼忘记回了
