### ISSUE TITLE
autoScale.label in usercontrol

### ISSUE THREAD

**Issue by RRRRossi** [hlz2516/AutoScaleHelper#6]
下载学习了autoScale的测试案例，我发现对于label字体没能有效的缩放，修改label的autosize属性为false，字体进行了放大，但是label放大后，原本的加粗效果没有了，我发现我自己的demo中，将label放入了usercontrol中，不知道是不是这个原因，导致了影响，或是还有其他什么设置，请大神讲解

**Comment by hlz2516** [comment]
1. 关于在usercontrol中的label没能有效缩放，我去看了下我的demo示例，是AutoScale实例创建后没有将AutoFont置为True导致的。AutoFont属性我也经常忘记设置，所以我现在一般都是直接调用有参构造函数，它会自动将AutoFont置为True并且设置容器。
2. 关于label放大后加粗效果没有了，可能是你的AutoScaleHelper没有升级到1.0.6版本及以上，在我这里是没有这个问题的。
